version: 2
formats: all
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
python:
   version: 3.8
   install:
      - requirements: docs/requirements.txt
      - requirements: requirements.txt
      - requirements: requirements-dev.txt